# Generated by Django 2.0.7 on 2018-07-14 01:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 14, 1, 1, 38, 112437, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
